services:
  {{ cookiecutter.project_slut }}-devenv:
    container_name: {{ cookiecutter.project_slut }}-devenv
    build:
      context: .devenv/
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
        USER_NAME: ${USER_NAME}
        DOTFILES_REPO: ${DOTFILES_REPO}
        DOTFILES_BRANCH: ${DOTFILES_BRANCH}
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}/:/home/${USER_NAME}/project
      - ${HOME}/.ssh/:/home/${USER_NAME}/.ssh:ro
    {% if cookiecutter.env_vars["array"] | length != 0 -%}
    environment:
      {% for env in cookiecutter.env_vars["array"] -%}
      - {{ env }}: {{'${'}}{{ env }}{{'}'}}
      {% endfor -%}
    {%- endif -%}
